Refactor for scraped
everypolitician-scrapers/argentina-diputados pull request #2
Opened 2016-12-08 15:18 UTC by ondenman

This is a step towards scraping the legislature with the new term dates. (See Senate: https://github.com/everypolitician-scrapers/argentina-senate/commit/a93b937ac40714806062e172986567091a529464)

2016-12-08 17:16 UTC, chrismytton requested changes

2016-12-08 17:16 UTC, chrismytton commented on Gemfile
> +ruby '2.3.1'
I think it probably makes sense to use the latest Ruby version, which is currently [2.3.3](https://www.ruby-lang.org/en/downloads/) :)

2016-12-08 17:16 UTC, chrismytton commented on lib/member.rb
> +    @section ||= MemberSection.new(response: response, noko: noko)
I think the `@section ||=` bit here (and the `@page` version below) are probably unnecessary optimizations at this stage. Probably best to drop them for now until they prove they are needed.

2016-12-08 17:16 UTC, chrismytton commented on lib/member.rb
> +    @section ||= MemberSection.new(response: response, noko: noko)
Passing `noko: noko` is redundant as the `MemberSection` will automatically create an identical `noko` object from the response you're passing in. So you can drop that parameter.

2016-12-08 17:16 UTC, chrismytton commented on lib/member.rb
> +class Member < Scraped::HTML
Hmm, I don't think it makes sense for `Member` to be a subclass of `Scraped::HTML`. You're quite right to create a `Member` class here - top level concepts like `Member` should be reserved for classes that pull together different concepts.

I think for this we probably want a plain `Member` class without a parent which implements a `#to_h` method which returns the information from the `MemberSection` class with the information from the `MemberPage` class.

2016-12-08 17:16 UTC, chrismytton commented on lib/member_page.rb
> +    noko.xpath('//div[@class="col-sm-12 col-md-2 distrito"]/following-sibling::div[@class="col-sm-12 col-md-4"]/h1/text()')
This and the selectors below seem to be very specific. Are the bootstrap classes (`col-*`) actually _required_ for this to work?

2016-12-08 17:16 UTC, chrismytton commented on lib/member_section.rb
> +     URI.join(url, noko.attr('href')).to_s
Looks like the indentation has gone a bit awry here :)

2016-12-08 17:16 UTC, chrismytton commented on scraper.rb
> +  ].map(&:to_h).reduce(&:merge)
I think this logic can be pushed down into the `Member` class as discussed in my comments above.

2017-07-07 16:44 UTC, ondenman commented
Closing this as it's a bit long winded. I've opened an issue in ep-data https://github.com/everypolitician/everypolitician/issues/601

2017-07-07 16:44 UTC, closed without merging